@sgs_localhost = http://localhost:5000

### GetSatellites

GET {{sgs_localhost}}/api/Satellite/
Accept: application/json

###

### GetSatelliteById

GET {{sgs_localhost}}/api/Satellite/6
Accept: application/json

###

### CreateSatellite

POST {{sgs_localhost}}/api/Satellite/
Content-Type: application/json

{
  "satelliteId": "SAT-021",
  "missionId": 2,
  "country": "USA"
}

###

### UpdateSatellite

PUT {{sgs_localhost}}/api/Satellite/6
Content-Type: application/json

{
  "status": 2,
  "missionId": 1
}