// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using sat_ground_station.Repository;

#nullable disable

namespace sat_ground_station.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260922195611_Add_Tables")]
    partial class Add_Tables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("sat_ground_station.Models.Alert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BatteryLevel")
                        .HasColumnType("text")
                        .HasColumnName("batteryLevel");

                    b.Property<int>("SatelliteId")
                        .HasColumnType("integer")
                        .HasColumnName("satelliteId");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("severity");

                    b.Property<string>("TemperatureLevel")
                        .HasColumnType("text")
                        .HasColumnName("temperatureLevel");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<string>("VelocityLevel")
                        .HasColumnType("text")
                        .HasColumnName("velocityLevel");

                    b.HasKey("Id");

                    b.ToTable("Alert");
                });

            modelBuilder.Entity("sat_ground_station.Models.Mission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("Mission");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Exploration mission",
                            Name = "Explorer",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Weather monitoring mission",
                            Name = "Weather",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Communication mission",
                            Name = "Communication",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Navigation mission",
                            Name = "Navigation",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Scientific research mission",
                            Name = "Science",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Earth imaging mission",
                            Name = "Imaging",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Tracking mission",
                            Name = "Tracking",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Research mission",
                            Name = "Research",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Monitoring mission",
                            Name = "Defense",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Technology demonstration mission",
                            Name = "Technology",
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("sat_ground_station.Models.Satellite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Country");

                    b.Property<int>("MissionId")
                        .HasColumnType("integer")
                        .HasColumnName("missionId");

                    b.Property<string>("SatelliteId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("satelliteId");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("MissionId");

                    b.ToTable("Satellite");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "US",
                            MissionId = 1,
                            SatelliteId = "SAT-001-Explorer",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 2,
                            Country = "US",
                            MissionId = 1,
                            SatelliteId = "SAT-002-Explorer",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 3,
                            Country = "US",
                            MissionId = 2,
                            SatelliteId = "SAT-003-Weather",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 4,
                            Country = "US",
                            MissionId = 2,
                            SatelliteId = "SAT-004-Weather",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 5,
                            Country = "US",
                            MissionId = 3,
                            SatelliteId = "SAT-005-Communication",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 6,
                            Country = "US",
                            MissionId = 3,
                            SatelliteId = "SAT-006-Communication",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 7,
                            Country = "US",
                            MissionId = 4,
                            SatelliteId = "SAT-007-Navigation",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 8,
                            Country = "US",
                            MissionId = 4,
                            SatelliteId = "SAT-008-Navigation",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 9,
                            Country = "US",
                            MissionId = 5,
                            SatelliteId = "SAT-009-Science",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 10,
                            Country = "US",
                            MissionId = 5,
                            SatelliteId = "SAT-010-Science",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 11,
                            Country = "US",
                            MissionId = 6,
                            SatelliteId = "SAT-011-Imaging",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 12,
                            Country = "US",
                            MissionId = 6,
                            SatelliteId = "SAT-012-Imaging",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 13,
                            Country = "US",
                            MissionId = 7,
                            SatelliteId = "SAT-013-Tracking",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 14,
                            Country = "US",
                            MissionId = 7,
                            SatelliteId = "SAT-014-Tracking",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 15,
                            Country = "US",
                            MissionId = 8,
                            SatelliteId = "SAT-015-Research",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 16,
                            Country = "US",
                            MissionId = 8,
                            SatelliteId = "SAT-016-Research",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 17,
                            Country = "US",
                            MissionId = 9,
                            SatelliteId = "SAT-017-Defense",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 18,
                            Country = "US",
                            MissionId = 9,
                            SatelliteId = "SAT-018-Defense",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 19,
                            Country = "US",
                            MissionId = 10,
                            SatelliteId = "SAT-019-Technology",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 20,
                            Country = "US",
                            MissionId = 10,
                            SatelliteId = "SAT-020-Technology",
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("sat_ground_station.Models.Telemetry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Altitude")
                        .HasColumnType("integer")
                        .HasColumnName("altitude");

                    b.Property<int>("BatteryLevel")
                        .HasColumnType("integer")
                        .HasColumnName("batteryLevel");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<int>("SatelliteId")
                        .HasColumnType("integer")
                        .HasColumnName("satalliteId");

                    b.Property<int>("Temperature")
                        .HasColumnType("integer")
                        .HasColumnName("temperature");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<int>("Velocity")
                        .HasColumnType("integer")
                        .HasColumnName("velocity");

                    b.HasKey("Id");

                    b.ToTable("Telemetry");
                });

            modelBuilder.Entity("sat_ground_station.Models.Satellite", b =>
                {
                    b.HasOne("sat_ground_station.Models.Mission", "Mission")
                        .WithMany("Satellites")
                        .HasForeignKey("MissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mission");
                });

            modelBuilder.Entity("sat_ground_station.Models.Mission", b =>
                {
                    b.Navigation("Satellites");
                });
#pragma warning restore 612, 618
        }
    }
}
